import React, { useEffect, useState } from "react";
import { Mail, User } from "lucide-react";
import { useAuth } from "../../context/AuthContext.jsx";

const statusText = { new: "Mới", in_progress: "Đang xử lý", resolved: "Đã giải quyết", active: "Đang hoạt động", cancelled: "Đã hủy" };
function ActivityTable({ title, rows, columns, empty }) { return <section className="account-section"><h3>{title}</h3><div className="admin-table-wrap"><table className="admin-table"><thead><tr>{columns.map((column) => <th key={column.label}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id || `${row.account_id}-${row.project_id}`}>{columns.map((column) => <td key={column.label}>{column.render(row)}</td>)}</tr>)}{!rows.length && <tr><td colSpan={columns.length} className="admin-table-empty">{empty}</td></tr>}</tbody></table></div></section>; }

export default function Profile() {
  const { user, isAdmin } = useAuth(); const [overview, setOverview] = useState({ interests: [], purchases: [], consultations: [] }); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/account-overview", { credentials: "include" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "Không thể tải dữ liệu tài khoản."); setOverview(body.data); }).catch((requestError) => setError(requestError.message)); }, []);
  const accountColumn = isAdmin ? [{ label: "Người dùng", render: (row) => <><strong>{row.account_name}</strong><div className="admin-table-sub">{row.account_email}</div></> }] : [];
  const date = (value) => new Date(value).toLocaleDateString("vi-VN");
  return <div><h2 className="admin-section-title profile-heading">{isAdmin ? "Hồ sơ quản lý" : "Tài khoản của tôi"}</h2><div className="profile-card"><div className="profile-avatar"><User size={26} /></div><div><div className="profile-name">{user.name}</div><div className="profile-meta"><Mail size={13} />{user.email}</div><span className="role-badge">{isAdmin ? "Quản lý" : "Người dùng"}</span></div></div>{error && <p className="form-error">{error}</p>}<ActivityTable title={isAdmin ? "Dự án được quan tâm" : "Dự án quan tâm"} rows={overview.interests} empty="Chưa có dự án nào được quan tâm." columns={[...accountColumn, { label: "Dự án", render: (row) => row.project_name }, { label: "Thời gian", render: (row) => date(row.created_at) }]} /><ActivityTable title="Dự án đã mua" rows={overview.purchases} empty="Chưa có dự án đã mua." columns={[...accountColumn, { label: "Dự án", render: (row) => row.project_name }, { label: "Trạng thái", render: (row) => statusText[row.status] || row.status }, { label: "Thời gian", render: (row) => date(row.created_at) }]} /><ActivityTable title={isAdmin ? "Tư vấn của người dùng" : "Tư vấn của bạn"} rows={overview.consultations} empty="Chưa có yêu cầu tư vấn nào." columns={[...accountColumn, { label: "Nội dung", render: (row) => row.message }, { label: "Trạng thái", render: (row) => statusText[row.status] || row.status }]} /></div>;
}
